import * as fs from "fs";
import * as path from "path";
import type { HandlerContext } from "./types.js";

export async function handleReorderPlugin(ctx: HandlerContext): Promise<string> {
  const { input, projectPath, changeLog } = ctx;
  const pluginName = (input.plugin_name as string | undefined)?.trim();
  const position = input.position as string;
  const relativePlugin = input.relative_plugin as string | undefined;

  if (!pluginName) return JSON.stringify({ error: "plugin_name is required" });
  if ((position === "before" || position === "after") && !relativePlugin) {
    return JSON.stringify({ error: `relative_plugin is required when position is '${position}'` });
  }

  try {
    const pluginsJsPath = path.join(projectPath, "js", "plugins.js");
    if (!fs.existsSync(pluginsJsPath)) return JSON.stringify({ error: "js/plugins.js not found" });

    const content = fs.readFileSync(pluginsJsPath, "utf-8");
    const match = content.match(/\$plugins\s*=\s*(\[[\s\S]*?\]);/);
    if (!match) return JSON.stringify({ error: "Could not parse plugins.js" });

    const plugins = JSON.parse(match[1]) as Array<Record<string, unknown>>;
    const pluginIdx = plugins.findIndex((p) => p.name === pluginName);
    if (pluginIdx === -1) return JSON.stringify({ error: `Plugin '${pluginName}' not found` });

    const oldIndex = pluginIdx;
    const [plugin] = plugins.splice(pluginIdx, 1);

    let newIndex: number;
    if (position === "first") {
      plugins.unshift(plugin);
      newIndex = 0;
    } else if (position === "last") {
      plugins.push(plugin);
      newIndex = plugins.length - 1;
    } else {
      const refIdx = plugins.findIndex((p) => p.name === relativePlugin);
      if (refIdx === -1) return JSON.stringify({ error: `Relative plugin '${relativePlugin}' not found` });
      const insertAt = position === "before" ? refIdx : refIdx + 1;
      plugins.splice(insertAt, 0, plugin);
      newIndex = insertAt;
    }

    const lines = plugins.map((p) => JSON.stringify(p)).join(",\n");
    const out = `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${lines}\n];\n`;
    fs.writeFileSync(pluginsJsPath, out, "utf-8");

    changeLog.append({
      tool: "reorder-plugin",
      entityType: "Plugin",
      action: "update",
      summary: `Plugin '${pluginName}' moved from index ${oldIndex} to ${newIndex}`,
    });

    return JSON.stringify({ success: true, plugin_name: pluginName, old_index: oldIndex, new_index: newIndex });
  } catch (error) {
    return JSON.stringify({ error: (error as Error).message });
  }
}
