import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { RPGMakerReader } from "../../src/adapters/mz/reader.js";
import { RPGMakerWriter } from "../../src/adapters/mz/writer.js";
import { RPGMakerDebugBridge } from "../../src/adapters/mz/debug-bridge.js";
import { ChangeLog } from "../../src/core/change-log.js";
import { handleManagePlugins } from "../../src/adapters/mz/handlers/manage-plugins.js";
import type { HandlerContext } from "../../src/adapters/mz/handlers/types.js";

const PLUGINS_JS_CONTENT = `// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginA","status":true,"description":"Alpha","parameters":{}},
{"name":"PluginB","status":false,"description":"Beta","parameters":{}}
];
`;

function createTempProject(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rpgmaker-plugins-"));
  const jsDir = path.join(dir, "js");
  const pluginsDir = path.join(jsDir, "plugins");
  fs.mkdirSync(path.join(dir, "data"), { recursive: true });
  fs.mkdirSync(jsDir, { recursive: true });
  fs.mkdirSync(pluginsDir, { recursive: true });

  fs.writeFileSync(path.join(jsDir, "plugins.js"), PLUGINS_JS_CONTENT, "utf-8");
  fs.writeFileSync(path.join(pluginsDir, "PluginA.js"), "// PluginA", "utf-8");

  return dir;
}

function makeCtx(dir: string, input: Record<string, unknown>): HandlerContext {
  return {
    reader: new RPGMakerReader({ projectPath: dir }),
    writer: new RPGMakerWriter({ projectPath: dir, createBackup: false }),
    input,
    projectPath: dir,
    debugBridge: new RPGMakerDebugBridge(),
    changeLog: new ChangeLog(dir),
    debug: false,
  };
}

describe("handleManagePlugins", () => {
  let dir: string;

  beforeEach(() => { dir = createTempProject(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  it("lists all plugins", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "list" })));
    expect(result.success).toBe(true);
    expect(result.count).toBe(2);
    expect(result.plugins.map((p: { name: string }) => p.name)).toEqual(["PluginA", "PluginB"]);
  });

  it("enables a disabled plugin", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "enable", plugin_name: "PluginB" })));
    expect(result.success).toBe(true);
    expect(result.status).toBe(true);

    const listed = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "list" })));
    const pluginB = listed.plugins.find((p: { name: string }) => p.name === "PluginB");
    expect(pluginB.status).toBe(true);
  });

  it("disables an enabled plugin", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "disable", plugin_name: "PluginA" })));
    expect(result.success).toBe(true);
    expect(result.status).toBe(false);
  });

  it("deletes a plugin from registry and removes its file", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "delete", plugin_name: "PluginA" })));
    expect(result.success).toBe(true);
    expect(result.removed_from_registry).toBe(true);
    expect(result.file_deleted).toBe(true);
    expect(fs.existsSync(path.join(dir, "js", "plugins", "PluginA.js"))).toBe(false);
  });

  it("deletes a plugin that has no file (registry-only)", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "delete", plugin_name: "PluginB" })));
    expect(result.success).toBe(true);
    expect(result.removed_from_registry).toBe(true);
    expect(result.file_deleted).toBe(false);
  });

  it("returns error when enabling a plugin not in registry", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "enable", plugin_name: "Ghost" })));
    expect(result.error).toBeDefined();
  });

  it("returns error when deleting a plugin that doesn't exist anywhere", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "delete", plugin_name: "Nonexistent" })));
    expect(result.error).toBeDefined();
  });

  it("returns error for unknown action", async () => {
    const result = JSON.parse(await handleManagePlugins(makeCtx(dir, { action: "purge" })));
    expect(result.error).toBeDefined();
  });

  it("appends to change log on enable", async () => {
    const ctx = makeCtx(dir, { action: "enable", plugin_name: "PluginB" });
    await handleManagePlugins(ctx);
    const entries = ctx.changeLog.read();
    expect(entries[0].tool).toBe("manage-plugins");
  });
});
