/**
 * Plugin integration tests.
 *
 * Covers:
 *  - Plugin template output (syntax, version, commands)
 *  - setup-debug-plugin e2e on a temp project
 *  - All runtime handlers: happy path, not-connected, timeout
 *  - HTTP bridge endpoints: /ping command dispatch, /ack, /gamestate, /log, /state
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import * as http from "http";
import { RPGMakerDebugBridge } from "../../src/rpgmaker/debug-bridge.js";
import { RPGMakerWriter } from "../../src/rpgmaker/writer.js";
import { RPGMakerReader } from "../../src/rpgmaker/reader.js";
import { RPGMakerValidator } from "../../src/rpgmaker/validator.js";
import { PluginTemplates } from "../../src/templates/plugin-template.js";
import { ChangeLog } from "../../src/rpgmaker/change-log.js";
import {
  handleSetupDebugPlugin,
  handleCreatePlugin,
} from "../../src/handlers/plugin.js";
import {
  handleGetGameState,
  handleSetSwitch,
  handleSetVariable,
  handleTeleportPlayer,
  handleSaveGame,
  handleStartEncounter,
  handleLoadGame,
  handleSetPartyState,
  handleRunBattleSuite,
} from "../../src/handlers/debug.js";
import type { HandlerContext } from "../../src/handlers/types.js";
import type { GameState } from "../../src/rpgmaker/debug-bridge.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTempProject(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rpgmaker-plugin-test-"));
  const dataDir = path.join(dir, "data");
  const pluginsDir = path.join(dir, "js", "plugins");
  fs.mkdirSync(dataDir, { recursive: true });
  fs.mkdirSync(pluginsDir, { recursive: true });

  // Minimal required data files
  fs.writeFileSync(path.join(dataDir, "Troops.json"),  JSON.stringify([null]), "utf-8");
  fs.writeFileSync(path.join(dataDir, "Enemies.json"), JSON.stringify([null]), "utf-8");
  fs.writeFileSync(path.join(dataDir, "System.json"),  JSON.stringify({ gameTitle: "Test", versionId: 1 }), "utf-8");

  // Minimal plugins.js (empty list — simulates a fresh project)
  const jsDir = path.join(dir, "js");
  fs.writeFileSync(
    path.join(jsDir, "plugins.js"),
    "// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[];\n",
    "utf-8",
  );

  return dir;
}

function makeContext(dir: string, bridge?: RPGMakerDebugBridge): HandlerContext {
  return {
    projectPath: dir,
    reader: new RPGMakerReader({ projectPath: dir }),
    writer: new RPGMakerWriter({ projectPath: dir, createBackup: false }),
    debugBridge: bridge ?? new RPGMakerDebugBridge(),
    changeLog: new ChangeLog(dir),
    input: {},
    debug: false,
  };
}

// ---------------------------------------------------------------------------
// Plugin template
// ---------------------------------------------------------------------------

describe("PluginTemplates.debugBridge", () => {
  const code = PluginTemplates.debugBridge(9001);

  it("produces valid JavaScript", () => {
    const result = RPGMakerValidator.validateJavaScript(code);
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it("declares version 2.1.0", () => {
    expect(code).toContain("@version 2.1.0");
  });

  it("contains all 6 commands in the dispatcher", () => {
    expect(code).toContain('"start_battle"');
    expect(code).toContain('"set_switch"');
    expect(code).toContain('"set_variable"');
    expect(code).toContain('"teleport"');
    expect(code).toContain('"get_state"');
    expect(code).toContain('"save_game"');
    expect(code).toContain('"advance_dialogue"');
  });

  it("reports game state to /gamestate endpoint", () => {
    expect(code).toContain('bridgeUrl + "/gamestate"');
  });

  it("sends ack to /ack endpoint", () => {
    expect(code).toContain('bridgeUrl + "/ack"');
  });

  it("polls /ping endpoint", () => {
    expect(code).toContain('bridgeUrl + "/ping"');
  });

  it("uses the provided port", () => {
    const code8080 = PluginTemplates.debugBridge(8080);
    expect(code8080).toContain("http://127.0.0.1:8080");
  });

  it("has gameReady guard in startBattle", () => {
    expect(code).toContain("if (!gameReady)");
  });

  it("has isInBattle guard to prevent concurrent battles", () => {
    expect(code).toContain("if (isInBattle)");
  });

  it("wraps dispatch in try/catch so errors post to /log", () => {
    // The dispatch function has a catch that posts to /log
    expect(code).toContain('xhrPost(bridgeUrl + "/log"');
  });
});

// ---------------------------------------------------------------------------
// setup-debug-plugin e2e
// ---------------------------------------------------------------------------

describe("handleSetupDebugPlugin", () => {
  let dir: string;

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("writes RPGMakerDebugger.js to js/plugins/", async () => {
    dir = makeTempProject();
    const ctx = makeContext(dir);
    const result = JSON.parse(await handleSetupDebugPlugin(ctx));

    expect(result.success).toBe(true);
    const pluginPath = path.join(dir, "js", "plugins", "RPGMakerDebugger.js");
    expect(fs.existsSync(pluginPath)).toBe(true);
  });

  it("registers RPGMakerDebugger as enabled in plugins.js", async () => {
    dir = makeTempProject();
    const ctx = makeContext(dir);
    await handleSetupDebugPlugin(ctx);

    const pluginsJs = fs.readFileSync(path.join(dir, "js", "plugins.js"), "utf-8");
    const match = pluginsJs.match(/\$plugins\s*=\s*\[[\s\S]*\]/);
    expect(match).not.toBeNull();
    const plugins = JSON.parse(pluginsJs.match(/(\[[\s\S]*\])/)?.[1] ?? "[]") as Array<{ name: string; status: boolean }>;
    const debugger_ = plugins.find((p) => p.name === "RPGMakerDebugger");
    expect(debugger_).toBeDefined();
    expect(debugger_!.status).toBe(true);
  });

  it("also registers pre-existing plugins in js/plugins/ as disabled", async () => {
    dir = makeTempProject();
    // Place two pre-existing plugins in the folder
    fs.writeFileSync(path.join(dir, "js", "plugins", "MyPlugin.js"), "/* test */", "utf-8");
    fs.writeFileSync(path.join(dir, "js", "plugins", "AnotherPlugin.js"), "/* test */", "utf-8");

    const ctx = makeContext(dir);
    const result = JSON.parse(await handleSetupDebugPlugin(ctx));

    expect(result.synced_plugins).toContain("MyPlugin");
    expect(result.synced_plugins).toContain("AnotherPlugin");

    const pluginsJs = fs.readFileSync(path.join(dir, "js", "plugins.js"), "utf-8");
    expect(pluginsJs).toContain('"MyPlugin"');
    expect(pluginsJs).toContain('"AnotherPlugin"');
    // Pre-existing plugins are disabled; only the debugger is enabled
    const plugins = JSON.parse(pluginsJs.match(/(\[[\s\S]*\])/)?.[1] ?? "[]") as Array<{ name: string; status: boolean }>;
    const myPlugin = plugins.find((p) => p.name === "MyPlugin");
    expect(myPlugin!.status).toBe(false);
  });

  it("is idempotent: calling twice reports 'updated' and does not duplicate", async () => {
    dir = makeTempProject();
    const ctx = makeContext(dir);
    await handleSetupDebugPlugin(ctx);
    const result2 = JSON.parse(await handleSetupDebugPlugin(makeContext(dir)));

    expect(result2.message).toContain("updated");

    const pluginsJs = fs.readFileSync(path.join(dir, "js", "plugins.js"), "utf-8");
    const plugins = JSON.parse(pluginsJs.match(/(\[[\s\S]*\])/)?.[1] ?? "[]") as Array<{ name: string }>;
    const debuggerEntries = plugins.filter((p) => p.name === "RPGMakerDebugger");
    expect(debuggerEntries).toHaveLength(1);
  });

  it("plugin code validates as JavaScript", async () => {
    dir = makeTempProject();
    const ctx = makeContext(dir);
    await handleSetupDebugPlugin(ctx);

    const code = fs.readFileSync(path.join(dir, "js", "plugins", "RPGMakerDebugger.js"), "utf-8");
    const result = RPGMakerValidator.validateJavaScript(code);
    expect(result.valid).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Runtime handlers — not-connected guard
// ---------------------------------------------------------------------------

describe("Runtime handlers — not connected", () => {
  let dir: string;
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it.each([
    ["get-game-state",  async (ctx: HandlerContext) => handleGetGameState(ctx)],
    ["set-switch",      async (ctx: HandlerContext) => handleSetSwitch({ ...ctx, input: { id: 1, value: true } })],
    ["set-variable",    async (ctx: HandlerContext) => handleSetVariable({ ...ctx, input: { id: 1, value: 42 } })],
    ["teleport-player", async (ctx: HandlerContext) => handleTeleportPlayer({ ...ctx, input: { map_id: 1, x: 5, y: 5 } })],
    ["save-game",       async (ctx: HandlerContext) => handleSaveGame(ctx)],
    ["start-encounter", async (ctx: HandlerContext) => handleStartEncounter({ ...ctx, input: { troop_id: 1 } })],
  ])("%s returns error JSON when game is not connected", async (_, fn) => {
    dir = makeTempProject();
    const ctx = makeContext(dir, new RPGMakerDebugBridge());
    const result = JSON.parse(await fn(ctx));
    expect(result.error).toMatch(/not connected|Game not connected/i);
  });
});

// ---------------------------------------------------------------------------
// Runtime handlers — happy path (auto-resolving bridge)
// ---------------------------------------------------------------------------

describe("Runtime handlers — happy path", () => {
  let dir: string;

  beforeEach(() => { dir = makeTempProject(); });
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  function connectedBridge(): RPGMakerDebugBridge {
    const b = new RPGMakerDebugBridge();
    b.markConnected();
    return b;
  }

  it("get-game-state returns state from bridge", async () => {
    const bridge = connectedBridge();
    const state: GameState = {
      mapId: 2, playerX: 4, playerY: 7, gold: 250,
      partyMembers: [{ name: "Hero", hp: 300, mhp: 300, level: 3 }],
      inBattle: false, timestamp: new Date().toISOString(),
    };
    // Auto-resolve: set game state after brief delay
    setTimeout(() => bridge.setGameState(state), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = {};
    const result = JSON.parse(await handleGetGameState(ctx));

    expect(result.success).toBe(true);
    expect(result.state.mapId).toBe(2);
    expect(result.state.gold).toBe(250);
    expect(result.state.partyMembers[0].name).toBe("Hero");
  });

  it("set-switch sends correct command and resolves on ack", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { id: 5, value: true };
    const result = JSON.parse(await handleSetSwitch(ctx));

    expect(result.success).toBe(true);
    expect(result.switch_id).toBe(5);
    expect(result.value).toBe(true);
    // Command should be cleared after ack
    expect(bridge.getCommand()).toBeNull();
  });

  it("set-switch writes correct command to bridge", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { id: 12, value: false };

    // Check command before resolving
    let capturedCommand: ReturnType<typeof bridge.getCommand> = null;
    const origResolve = bridge.resolveAck.bind(bridge);
    bridge.resolveAck = () => {
      capturedCommand = bridge.getCommand();
      origResolve();
    };

    await handleSetSwitch(ctx);
    // At the moment resolveAck fires, command is still set
    expect(capturedCommand?.command).toBe("set_switch");
    expect(capturedCommand?.args).toEqual({ id: 12, value: false });
  });

  it("set-variable sends correct command with numeric value", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { id: 3, value: 999 };
    const result = JSON.parse(await handleSetVariable(ctx));

    expect(result.success).toBe(true);
    expect(result.variable_id).toBe(3);
    expect(result.value).toBe(999);
  });

  it("set-variable sends correct command with string value", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { id: 7, value: "hero_name" };
    const result = JSON.parse(await handleSetVariable(ctx));

    expect(result.success).toBe(true);
    expect(result.value).toBe("hero_name");
  });

  it("teleport-player sends correct command with explicit direction", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { map_id: 3, x: 10, y: 15, direction: 8 };
    const result = JSON.parse(await handleTeleportPlayer(ctx));

    expect(result.success).toBe(true);
    expect(result.map_id).toBe(3);
    expect(result.x).toBe(10);
    expect(result.y).toBe(15);
    expect(result.direction).toBe(8);
  });

  it("teleport-player defaults direction to 0 when omitted", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { map_id: 1, x: 5, y: 5 };
    const result = JSON.parse(await handleTeleportPlayer(ctx));

    expect(result.direction).toBe(0);
  });

  it("save-game uses default slot 98 when slot omitted", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = {};
    const result = JSON.parse(await handleSaveGame(ctx));

    expect(result.success).toBe(true);
    expect(result.slot).toBe(98);
  });

  it("save-game uses provided slot", async () => {
    const bridge = connectedBridge();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { slot: 5 };
    const result = JSON.parse(await handleSaveGame(ctx));

    expect(result.slot).toBe(5);
  });
});

// ---------------------------------------------------------------------------
// Runtime handlers — timeout behaviour
// ---------------------------------------------------------------------------

describe("Runtime handlers — timeout", () => {
  let dir: string;
  beforeEach(() => { dir = makeTempProject(); });
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it("set-switch returns error JSON when ack never arrives", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();

    const ctx = makeContext(dir, bridge);
    ctx.input = { id: 1, value: true };

    // Override waitForAck to use a short timeout
    const orig = bridge.waitForAck.bind(bridge);
    bridge.waitForAck = () => orig(100); // 100ms instead of 10s

    const result = JSON.parse(await handleSetSwitch(ctx));
    expect(result.error).toMatch(/timed out/i);
  });

  it("get-game-state returns error when game state never arrives", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();

    const ctx = makeContext(dir, bridge);
    ctx.input = {};

    const orig = bridge.waitForGameState.bind(bridge);
    bridge.waitForGameState = () => orig(100);

    const result = JSON.parse(await handleGetGameState(ctx));
    expect(result.error).toMatch(/timed out/i);
  });
});

// ---------------------------------------------------------------------------
// HTTP bridge endpoints (in-process simulation)
// ---------------------------------------------------------------------------

describe("HTTP bridge endpoint simulation", () => {
  it("/ping with no command returns 204", async () => {
    const bridge = new RPGMakerDebugBridge();
    // Simulate what the HTTP handler does for GET /ping
    bridge.markConnected();
    const cmd = bridge.getCommand();
    expect(cmd).toBeNull();
    // 204 = no content
  });

  it("/ping with pending command returns the command JSON", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.setCommand("set_switch", { id: 3, value: true });
    const cmd = bridge.getCommand();
    expect(cmd).not.toBeNull();
    expect(JSON.stringify(cmd)).toContain("set_switch");
  });

  it("/ack resolves the pending waiter AND clears the command", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.setCommand("set_variable", { id: 1, value: 100 });

    let ackResolved = false;
    const waitPromise = bridge.waitForAck(2000).then((v) => { ackResolved = v; });

    // Simulate game posting to /ack
    bridge.resolveAck();
    await waitPromise;

    expect(ackResolved).toBe(true);
    expect(bridge.getCommand()).toBeNull(); // cleared by resolveAck
  });

  it("/gamestate resolves waitForGameState and clears command", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.setCommand("get_state", {});

    const state: GameState = {
      mapId: 5, playerX: 1, playerY: 2, gold: 0,
      partyMembers: [], inBattle: false,
      timestamp: new Date().toISOString(),
    };

    let resolved: GameState | null = null;
    const waitPromise = bridge.waitForGameState(2000).then((s) => { resolved = s; });

    // Simulate game posting to /gamestate
    bridge.setGameState(state);
    await waitPromise;

    expect(resolved!.mapId).toBe(5);
    expect(bridge.getCommand()).toBeNull(); // cleared by waitForGameState
  });

  it("/log appends events visible to waitForBattle", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.setCommand("start_battle", { troopId: 1 });

    const battlePromise = bridge.waitForBattle(2000);

    bridge.addEvent({ type: "battle_start", troopId: 1 });
    bridge.addEvent({ type: "action", subject: "Hero", target: "Slime" });
    bridge.setFinalState({ inBattle: false, battleOver: true, turn: 2, actors: [], enemies: [] });

    const result = await battlePromise;
    expect(result.success).toBe(true);
    expect(result.log.length).toBeGreaterThanOrEqual(2);
    expect(result.log[0].type).toBe("battle_start");
  });

  it("/state with inBattle=true does NOT resolve waitForBattle", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.setCommand("start_battle", { troopId: 1 });

    // Post a mid-battle state (still fighting)
    bridge.setFinalState({ inBattle: true, battleOver: false, turn: 1, actors: [], enemies: [] });

    // waitForBattle should NOT resolve yet (state has inBattle=true)
    const earlyResolved = await Promise.race([
      bridge.waitForBattle(50).then(() => "resolved"),
      new Promise<string>((r) => setTimeout(() => r("pending"), 80)),
    ]);
    expect(earlyResolved).toBe("pending");
  });

  it("multiple sequential ack waiters resolve one at a time", async () => {
    const bridge = new RPGMakerDebugBridge();
    const order: number[] = [];

    const p1 = bridge.waitForAck(2000).then(() => order.push(1));
    const p2 = bridge.waitForAck(2000).then(() => order.push(2));

    bridge.resolveAck(); // resolves p1
    await p1;
    expect(order).toEqual([1]);

    bridge.resolveAck(); // resolves p2
    await p2;
    expect(order).toEqual([1, 2]);
  });
});

// ---------------------------------------------------------------------------
// Change log integration
// ---------------------------------------------------------------------------

describe("Change log entries from runtime handlers", () => {
  let dir: string;
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it("set-switch appends a change log entry", async () => {
    dir = makeTempProject();
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { id: 7, value: true };
    await handleSetSwitch(ctx);

    const entries = ctx.changeLog.read({ limit: 5 });
    expect(entries.some((e) => e.tool === "set-switch" && e.entityId === 7)).toBe(true);
  });

  it("save-game appends a change log entry with the slot", async () => {
    dir = makeTempProject();
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { slot: 3 };
    await handleSaveGame(ctx);

    const entries = ctx.changeLog.read({ limit: 5 });
    expect(entries.some((e) => e.tool === "save-game" && e.entityId === 3)).toBe(true);
  });

  it("teleport-player appends a change log entry", async () => {
    dir = makeTempProject();
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { map_id: 4, x: 8, y: 3 };
    await handleTeleportPlayer(ctx);

    const entries = ctx.changeLog.read({ limit: 5 });
    const entry = entries.find((e) => e.tool === "teleport-player");
    expect(entry).toBeDefined();
    expect(entry!.summary).toContain("map 4");
  });
});

// ---------------------------------------------------------------------------
// load-game
// ---------------------------------------------------------------------------

describe("handleLoadGame", () => {
  let dir: string;
  beforeEach(() => { dir = makeTempProject(); });
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it("returns error when not connected", async () => {
    const ctx = makeContext(dir, new RPGMakerDebugBridge());
    const result = JSON.parse(await handleLoadGame(ctx));
    expect(result.error).toMatch(/not connected/i);
  });

  it("sends load_game command with default slot 98", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const state = {
      mapId: 1, playerX: 5, playerY: 5, gold: 100,
      partyMembers: [{ name: "Hero", hp: 400, mhp: 400, level: 5 }],
      inBattle: false, timestamp: new Date().toISOString(),
    };
    setTimeout(() => { bridge.setGameState(state); bridge.clearCommand(); }, 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = {};
    const result = JSON.parse(await handleLoadGame(ctx));

    expect(result.success).toBe(true);
    expect(result.slot).toBe(98);
    expect(result.state.mapId).toBe(1);
  });

  it("sends load_game command with specified slot", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const state = {
      mapId: 3, playerX: 10, playerY: 2, gold: 500,
      partyMembers: [], inBattle: false, timestamp: new Date().toISOString(),
    };
    let capturedSlot: unknown;
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { capturedSlot = args.slot; origSet(cmd, args); };
    setTimeout(() => { bridge.setGameState(state); bridge.clearCommand(); }, 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { slot: 5 };
    const result = JSON.parse(await handleLoadGame(ctx));

    expect(result.success).toBe(true);
    expect(result.slot).toBe(5);
    expect(capturedSlot).toBe(5);
  });

  it("returns error on timeout", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    // Never resolves game state — triggers timeout
    const ctx = makeContext(dir, bridge);
    ctx.input = {};
    const result = JSON.parse(await handleLoadGame({ ...ctx, debugBridge: Object.assign(bridge, {
      waitForGameState: async () => { throw new Error("Timed out waiting for game state"); },
    }) }));
    expect(result.error).toMatch(/timed out/i);
  });

  it("appends a change log entry", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const state = {
      mapId: 1, playerX: 0, playerY: 0, gold: 0,
      partyMembers: [], inBattle: false, timestamp: new Date().toISOString(),
    };
    setTimeout(() => { bridge.setGameState(state); bridge.clearCommand(); }, 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { slot: 7 };
    await handleLoadGame(ctx);

    const entries = ctx.changeLog.read({ limit: 5 });
    expect(entries.some((e) => e.tool === "load-game" && e.entityId === 7)).toBe(true);
  });

  it("plugin template contains load_game case", () => {
    const code = PluginTemplates.debugBridge(9001);
    expect(code).toContain('"load_game"');
    expect(code).toContain("DataManager.loadGame");
    expect(code).toContain("SceneManager.goto(Scene_Map)");
  });
});

// ---------------------------------------------------------------------------
// set-party-state
// ---------------------------------------------------------------------------

describe("handleSetPartyState", () => {
  let dir: string;
  beforeEach(() => { dir = makeTempProject(); });
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it("returns error when not connected", async () => {
    const ctx = makeContext(dir, new RPGMakerDebugBridge());
    const result = JSON.parse(await handleSetPartyState({ ...ctx, input: { hp_percent: 0.5 } }));
    expect(result.error).toMatch(/not connected/i);
  });

  it("rejects hp_percent out of range", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const ctx = makeContext(dir, bridge);
    ctx.input = { hp_percent: 1.5 };
    const result = JSON.parse(await handleSetPartyState(ctx));
    expect(result.error).toMatch(/hp_percent/i);
  });

  it("rejects mp_percent out of range", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const ctx = makeContext(dir, bridge);
    ctx.input = { mp_percent: -0.1 };
    const result = JSON.parse(await handleSetPartyState(ctx));
    expect(result.error).toMatch(/mp_percent/i);
  });

  it("sends set_party_state command with hp_percent", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    let captured: Record<string, unknown> = {};
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { captured = args; origSet(cmd, args); };
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { hp_percent: 0.25 };
    const result = JSON.parse(await handleSetPartyState(ctx));

    expect(result.success).toBe(true);
    expect(captured.hp_percent).toBe(0.25);
    expect(captured.actor_id).toBeUndefined();
  });

  it("sends set_party_state command targeting a specific actor", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    let captured: Record<string, unknown> = {};
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { captured = args; origSet(cmd, args); };
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { actor_id: 2, hp_percent: 0.1, mp_percent: 0.0 };
    const result = JSON.parse(await handleSetPartyState(ctx));

    expect(result.success).toBe(true);
    expect(captured.actor_id).toBe(2);
    expect(captured.hp_percent).toBe(0.1);
    expect(captured.mp_percent).toBe(0.0);
  });

  it("sends add_states and remove_states arrays", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    let captured: Record<string, unknown> = {};
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { captured = args; origSet(cmd, args); };
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { add_states: [4, 5], remove_states: [1] };
    await handleSetPartyState(ctx);

    expect(captured.add_states).toEqual([4, 5]);
    expect(captured.remove_states).toEqual([1]);
  });

  it("returns error on ack timeout", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    // Never resolves
    const ctx = makeContext(dir, bridge);
    ctx.input = { hp_percent: 0.5 };
    const result = JSON.parse(await handleSetPartyState({ ...ctx, debugBridge: Object.assign(bridge, {
      waitForAck: async () => false,
    }) }));
    expect(result.error).toMatch(/timed out/i);
  });

  it("appends a change log entry", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    setTimeout(() => bridge.resolveAck(), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { actor_id: 1, hp_percent: 0.5 };
    await handleSetPartyState(ctx);

    const entries = ctx.changeLog.read({ limit: 5 });
    const entry = entries.find((e) => e.tool === "set-party-state");
    expect(entry).toBeDefined();
    expect(entry!.summary).toContain("hp=50%");
  });

  it("plugin template contains set_party_state case with hp/mp/states logic", () => {
    const code = PluginTemplates.debugBridge(9001);
    expect(code).toContain('"set_party_state"');
    expect(code).toContain("actor.setHp");
    expect(code).toContain("actor.setMp");
    expect(code).toContain("actor.addState");
    expect(code).toContain("actor.removeState");
  });
});

// ---------------------------------------------------------------------------
// start-encounter action queue
// ---------------------------------------------------------------------------

describe("start-encounter action queue", () => {
  let dir: string;
  beforeEach(() => { dir = makeTempProject(); });
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it("passes actionQueue in start_battle command when actions provided", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    let captured: Record<string, unknown> = {};
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { captured = args; origSet(cmd, args); };
    // Resolve battle immediately
    setTimeout(() => bridge.setFinalState({
      inBattle: false, battleOver: true, turn: 1,
      actors: [{ name: "Hero", hp: 300, mhp: 400, mp: 50, mmp: 50, states: [] }],
      enemies: [],
    }), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = {
      troop_id: 1,
      actions: [
        [{ actor_id: 1, type: "skill", skill_id: 5 }],
        [{ type: "attack" }],
      ],
    };
    const result = JSON.parse(await handleStartEncounter(ctx));

    expect(result.success).toBe(true);
    expect(captured.actionQueue).toEqual([
      [{ actor_id: 1, type: "skill", skill_id: 5 }],
      [{ type: "attack" }],
    ]);
  });

  it("passes empty actionQueue when no actions provided", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    let captured: Record<string, unknown> = {};
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { captured = args; origSet(cmd, args); };
    setTimeout(() => bridge.setFinalState({
      inBattle: false, battleOver: true, turn: 1,
      actors: [], enemies: [],
    }), 50);

    const ctx = makeContext(dir, bridge);
    ctx.input = { troop_id: 1 };
    await handleStartEncounter(ctx);

    expect(captured.actionQueue).toEqual([]);
  });

  it("plugin template contains actionQueue variable and turnPlan logic", () => {
    const code = PluginTemplates.debugBridge(9001);
    expect(code).toContain("actionQueue");
    expect(code).toContain("turnPlan");
    expect(code).toContain("setSkill");
    expect(code).toContain("setGuard");
    expect(code).toContain("setItem");
  });
});

// ---------------------------------------------------------------------------
// run-battle-suite
// ---------------------------------------------------------------------------

describe("handleRunBattleSuite", () => {
  let dir: string;
  beforeEach(() => { dir = makeTempProject(); });
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  function makeFinalState(actorHp = 300) {
    return {
      inBattle: false, battleOver: true, turn: 3,
      actors: [{ name: "Reid", hp: actorHp, mhp: 544, mp: 80, mmp: 80, states: [] }],
      enemies: [{ name: "Duende", hp: 0, mhp: 200, mp: 0, mmp: 0, states: [] }],
    };
  }

  function autoResolvingBridge(runs: number, winResult = 0) {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    let callCount = 0;
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => {
      origSet(cmd, args);
      if (cmd === "set_party_state") {
        setTimeout(() => bridge.resolveAck(), 20);
      } else if (cmd === "start_battle") {
        setTimeout(() => {
          bridge.addEvent({ type: "battle_start", troopId: args.troopId });
          bridge.addEvent({ type: "action", subject: "Reid", subject_type: "actor", action: "Attack",
            target: "Duende", hpDamage: 150, hpBefore: 200, hpAfter: 50, alive: true, critical: false, formula: "a.atk", turn: 1 });
          bridge.addEvent({ type: "action", subject: "Duende", subject_type: "enemy", action: "Attack",
            target: "Reid", hpDamage: 80, hpBefore: 544, hpAfter: 464, alive: true, critical: false, formula: "a.atk", turn: 1 });
          bridge.addEvent({ type: "battle_end", result: callCount++ < runs ? winResult : 2 });
          bridge.setFinalState(makeFinalState(winResult === 0 ? 300 : 0));
        }, 30);
      }
    };
    return bridge;
  }

  it("returns error when not connected", async () => {
    const ctx = makeContext(dir, new RPGMakerDebugBridge());
    const result = JSON.parse(await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 2 } }));
    expect(result.error).toMatch(/not connected/i);
  });

  it("returns error without troop_id or enemy_id", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const ctx = makeContext(dir, bridge);
    const result = JSON.parse(await handleRunBattleSuite({ ...ctx, input: { runs: 3 } }));
    expect(result.error).toMatch(/troop_id|enemy_id/i);
  });

  it("runs the requested number of battles", async () => {
    const bridge = autoResolvingBridge(3);
    const ctx = makeContext(dir, bridge);
    const result = JSON.parse(await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 3 } }));
    expect(result.success).toBe(true);
    expect(result.runs).toBe(3);
    expect(result.summary.total_runs).toBe(3);
  });

  it("caps runs at 50", async () => {
    vi.useFakeTimers();
    try {
      const bridge = new RPGMakerDebugBridge();
      bridge.markConnected();
      bridge.setCommand = () => {};
      bridge.waitForAck = async () => true;
      bridge.waitForBattle = async () => ({
        success: true,
        log: [{ type: "battle_end", result: 0 }],
        state: makeFinalState(),
        summary: "ok",
      });
      const ctx = makeContext(dir, bridge);
      const handlePromise = handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 999 } });
      await vi.runAllTimersAsync();
      const result = JSON.parse(await handlePromise);
      expect(result.success).toBe(true);
      expect(result.runs).toBe(50);
    } finally {
      vi.useRealTimers();
    }
  });

  it("computes win_rate correctly", async () => {
    const bridge = new RPGMakerDebugBridge();
    bridge.markConnected();
    const origSet = RPGMakerDebugBridge.prototype.setCommand.bind(bridge);
    let callIdx = 0;
    bridge.setCommand = (cmd: string, args: Record<string, unknown>) => {
      origSet(cmd, args); // resets events/finalState each run
      if (cmd === "set_party_state") {
        setTimeout(() => bridge.resolveAck(), 20);
      } else if (cmd === "start_battle") {
        const win = callIdx++ < 3; // 3 wins, 1 loss
        setTimeout(() => {
          bridge.addEvent({ type: "battle_end", result: win ? 0 : 2 });
          bridge.setFinalState(makeFinalState(win ? 300 : 0));
        }, 30);
      }
    };
    const ctx = makeContext(dir, bridge);
    const result = JSON.parse(await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 4 } }));
    expect(result.summary.wins).toBe(3);
    expect(result.summary.losses).toBe(1);
    expect(result.summary.win_rate).toBe(0.75);
  });

  it("aggregates actor HP stats", async () => {
    const bridge = autoResolvingBridge(2);
    const ctx = makeContext(dir, bridge);
    const result = JSON.parse(await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 2 } }));
    const reid = result.summary.actors.find((a: { name: string }) => a.name === "Reid");
    expect(reid).toBeDefined();
    expect(typeof reid.avg_hp).toBe("number");
    expect(typeof reid.avg_hp_percent).toBe("number");
    expect(typeof reid.survival_rate).toBe("number");
  });

  it("splits damage into dealt/taken using subject_type", async () => {
    const bridge = autoResolvingBridge(1);
    const ctx = makeContext(dir, bridge);
    const result = JSON.parse(await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 1 } }));
    expect(result.summary.damage.avg_dealt).toBe(150); // Reid dealt 150
    expect(result.summary.damage.avg_taken).toBe(80);  // Duende dealt 80
  });

  it("passes party_state to set_party_state each run", async () => {
    const bridge = autoResolvingBridge(2);
    const capturedStates: Record<string, unknown>[] = [];
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => {
      if (cmd === "set_party_state") capturedStates.push({ ...args });
      origSet(cmd, args);
    };
    const ctx = makeContext(dir, bridge);
    await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 2, party_state: { hp_percent: 0.5 } } });
    expect(capturedStates).toHaveLength(2);
    expect(capturedStates.every(s => s.hp_percent === 0.5)).toBe(true);
  });

  it("defaults party_state to full HP/MP when omitted", async () => {
    const bridge = autoResolvingBridge(1);
    let capturedState: Record<string, unknown> = {};
    const origSet = bridge.setCommand.bind(bridge);
    bridge.setCommand = (cmd, args) => { if (cmd === "set_party_state") capturedState = { ...args }; origSet(cmd, args); };
    const ctx = makeContext(dir, bridge);
    await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 1 } });
    expect(capturedState.hp_percent).toBe(1.0);
    expect(capturedState.mp_percent).toBe(1.0);
  });

  it("appends a change log entry with win/loss summary", async () => {
    const bridge = autoResolvingBridge(2);
    const ctx = makeContext(dir, bridge);
    await handleRunBattleSuite({ ...ctx, input: { troop_id: 1, runs: 2 } });
    const entries = ctx.changeLog.read({ limit: 5 });
    const entry = entries.find(e => e.tool === "run-battle-suite");
    expect(entry).toBeDefined();
    expect(entry!.summary).toContain("W/");
  });

  it("plugin template uses canLose=true in BattleManager.setup", () => {
    const code = PluginTemplates.debugBridge(9001);
    expect(code).toContain("BattleManager.setup(troopId, true, true)");
  });

  it("plugin template includes subject_type in action events", () => {
    const code = PluginTemplates.debugBridge(9001);
    expect(code).toContain("subject_type");
    expect(code).toContain("isActorSide");
  });
});
